all: presentation

presentation: part1 part2

part1:
	pdflatex presentation1

part2:
	pdflatex presentation2

clean:
	rm -rf *.aux *.bbl *.blg *.log *.out *.toc *.lof *.lot *.vrb *.nav *.snm *.vrb *.dvi *.pdf

clear:
	rm -rf *.aux *.bbl *.blg *.log *.out *.toc *.lof *.lot *.nav *.snm *.vrb *.dvi 
