all: presentation

presentation:
		pdflatex presentation

clean:
	rm -rf *.aux *.bbl *.blg *.log *.out *.toc *.lof *.lot *.vrb *.nav *.snm *.vrb *.dvi *.pdf

clear:
	rm -rf *.aux *.bbl *.blg *.log *.out *.toc *.lof *.lot *.nav *.snm *.vrb *.dvi 
